### ISSUE TITLE
Enable custom hosting with custom entities

### ISSUE THREAD

**Issue by Gredelston** [open5e/open5e-api#118]
Paraphrasing a user story I heard from @augustjohnson:

> As a DM and a techy, I want to clone my own instance of open5e for my players, and add my own entities (items, monsters, ...) to it.
> 
> That's the vision more or less, but it implies that data and server are disconnected, and UI / API are self-hostable, and that there's a decently easy on-ramp for data creation.

What features are currently missing for this to be possible? I think we need some separation of "upstream" vs. "custom" entities. Beyond that, needs further investigation.

**Comment by augustjohnson** [comment]
Just spitballing here:

What if the /data was a reference and upon load could either target a folder of properly formatted json, or "upstream" which could be a new repo at something like /open5e/open5e-data, which would (by default) pull the main/head.

That solves the data source customization problem, and decouples the scare python API repo (for non-techy bugfixers) from the human accessible json repo.

This work would at least partially be by editing this:
https://github.com/open5e/open5e-api/blob/master/api/management/commands/importer.py
This:
https://github.com/open5e/open5e-api/blob/master/scripts/deploy.sh
And making sure this supports it all.
https://github.com/open5e/open5e-api/blob/master/api/management/commands/populatedb.py

**Comment by augustjohnson** [comment]
The self-hosted portion could be basically an all-in-one container build with API / UI / even database all up on a single container for simplicities sake, and a clean on-ramp for a custom data source. This on docker-hub would be pretty sick.

**Comment by eepMoody** [comment]
That all seems very reasonable to me! So far the project has already split once (from a monorepo to a separate API/UI) and it only seems to have improved things.

I'd need some advice on the best way to set it up, but would a good first start be creating an empty /open5e-data repo and hooking it up to DockerHub so people can start experimenting against it?

**Comment by augustjohnson** [comment]
Here's a more complete vision in user-story form.
As a technical, self-hosting DM who wants to provide resources for my team, I would like to run something simple, like:

> docker pull open5e-lite

Which would result in:
a local instance with port 8000 being the UI
port 8001 being the API
a SQLITE backend
all the data from ../local/data imported and made available.

So that I can provide my players a reliable, mostly immutable source of record for my campaign's custom items/classes/races/etc.

**Unsolved Question:** how do I provide a self-hoster a quick but easy interface to provide their own content to their own instance? Some sort of import process flow? Maybe that could be a new API endpoint?

**Comment by augustjohnson** [comment]
**Implementation suggestion:**
It shouldn't be too tough to make this succeed:
> docker pull ghcr.io/open5e/open5e-api
> docker pull ghcr.io/open5e/open5e

This would be the product of a few github actions to build and post our container image to github's container registry.

Making them talk to each other is a bit tougher. perhaps we could write a dockerfile that builds an image that's both the API and the UI on the same image? I would think that would live in "open5e" rather than the API though, which means there'd be an outbound reference to another repo, but that's all resolveable.

**Comment by augustjohnson** [comment]
I'm going to close this for now. I think the basic idea would be that a sufficiently technical user can just do docker-compose up, and the only file they have to edit is /api/management/commands/quickload.py with their custom directories.  Not perfect, but good enough. I don't think the local instance thing is that big of a deal.
