### ISSUE TITLE
Adjust/regenerate Spells to include Classes as an array

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e-api#285]
Currently this is only available as a string `"wizard, druid, cleric"`. It'd be great if it was an array of strings instead. `["wizard", "druid", "cleric"]` so that it can be better used for filtering, and parsed in cleverer ways on the frontend.

**Comment by daydin** [comment]
Hi! I'm interested in taking this on. If I understand it correctly, we need a new ListField type of thing in models instead of a TextField, which is what we have now for all of classes, archetypes, circles, and so on. Is that correct?  and then , dnd_class, archetype, and other fields can become a ListField type.

**Comment by augustjohnson** [comment]
Howdy @daydin thanks for showing the interest! So a few things have happened since this bug was originally logged.  First: "spell_lists" have been included. See here:
https://api-beta.open5e.com/v1/spells/magic-missile/ the spell_lists item includes (properly formated) ["sorcerer","wizard"] which is nice.
Second, the API_V2 is starting to spin up. I'm working on a standardized implementation of spell sets over there, which will be online fairly soon, which will result is fixing this.

I am concerned that splitting this existing (dnd_class) field open would end up breaking frontend stuff, so I don't believe editing that is a good idea. At this point, I think this issue can probably be considered closed. Let me know if you have a thought.

**Comment by augustjohnson** [comment]
Both v1 and v2 spells have classes as an array. The initial concern of this issue has been addressed.
