### ISSUE TITLE
Data file formatting

### ISSUE THREAD

**Issue by Sturlen** [open5e/open5e-api#403]
The current json file indentation does not appear to be any standard format, which makes it difficult to make a PRs that stick to this format. I've managed to match it by outputting a file with `json.dumps(indent=2)` and them removing two spaces from each line using `lines = [re.sub(r'^  ','', line) for line in lines]`

Instead it would be great if we agreed on a standard format and updated the unused `scripts/lint_json.py` to format files using this.

**Comment by Kordishal** [comment]
This would be useful yes. The current formatting is generated by the exporter with [this line](https://github.com/open5e/open5e-api/blob/97970b6620b534d8f7f6bd0af8c6cc6f727f8e6b/api_v2/management/commands/export.py#L178)

I am a bit confused why this django serializer creates this weird format for json serialization. It just says indent=2 which should give the same result. Would have to investigate why that is that then adjust it. Because otherwise the export would just be annoying if you have to format the json with an extra script after using the exporter.

**Comment by augustjohnson** [comment]
Django's code for producing these is here:
https://github.com/django/django/blob/main/django/core/serializers/json.py#L21

In addition, v2 will support form data entry using the admin features built into django (on localhost).
I think that the data file formats themselves are fine, I would like to see some better input and output formats though.
I will say that a trick I've got is that you import in whatever format works (i don't believe whitespace, order, or even field existence matters on import?) and then export it out again. That results in clean files.

I wonder if someone who is experienced writing linters could assist with this? I'm certainly not.

**Comment by augustjohnson** [comment]
I think the broad approach for adding data will be to copy/paste or add using the admin interface. The input format is actually fairly flexible, only the output is standardized by the django function above.

I have added ./scripts/data_test.py and it runs as part of the build to ensure that each file is valid json and that unicode characters are left out (at least for now, multi-language could make things weird).

I think there's a broad story on making data input easier, but that's outside of the scope of this ticket.  For now I'm calling this resolved.
