### ISSUE TITLE
Data origins

### ISSUE THREAD

**Issue by benjaminapetersen** [open5e/open5e-api#42]
Greetings!

Just curious where the original data comes from, for legal/copyright reasons.  There are several others resources that are also based on 5e SRD  ([such as 5e-database](https://github.com/adrpadua/5e-database)) .  What I cant figure out is if there is a root canonical data source that clearly does not include any copyrighted content (IE, no accidental inclusion of something WOTC specific).

If you have any insight into this would def appreciate it!

**Comment by eepMoody** [comment]
The original SRD data we use came from an OCR parsing of the SRD PDF that we obtained from another developer when we first kicked off the project. It's based on the first release of the SRD, but has since been updated based on the 5.1 SRD release

It's been modified and added to by contributions over time, so at this point it doesn't have a single definitive source. To the best of my knowledge it does not contain any non-SRD content, and if any has been included by accident we will remove it immediately.

The best way to be safe is to use the API directly, that way if there are any issues your app will instantly be updated. I can't make any guarantees about the data if you grab a snapshot at any given point of time. The safest thing to do there would be to grab a fresh copy of the SRD and make a direct copy.

**Comment by benjaminapetersen** [comment]
Great info, thanks! Great to have this clarified.

**Comment by benjaminapetersen** [comment]
One more Q!
The Kobold Press Tome of Beasts data is free to use?
https://raw.githubusercontent.com/eepMoody/open5e-api/master/data/tome_of_beasts/monsters.json

I'm not familiar with them, but didn't see anything on the website indicating the digital use is free:
https://koboldpress.com/kpstore/product/tome-of-beasts-for-5th-edition/

Thanks!

**Comment by RealDeuce** [comment]
Ok, this is a narcopost, but the OGL declaration in Tome of Beasts specifies:
> The Open content in this book includes the monster names, descriptions, monster statistics, and monster abilities."

Copyright section in ToB is:
> Open Game License v 1.0a Copyright 2000, Wizards of the Coast, Inc.
> System Reference Document 5.0 Copyright 2016, Wizards of the Coast, Inc.; Authors Mike Mearls, Jeremy Crawford, Chris Perkins, Rodney Thompson, Peter Lee, James Wyatt, Robert J. Schwalb, Bruce R. Cordell, Chris Sims, and Steve Townshend, based on original material by E. Gary Gygax and Dave Arneson.
> Tome of Beasts. Copyright 2016, Open Design; Authors Chris Harris, Dan Dillon, Rodrigo Garcia Carmona, and Wolfgang Baur.
