### ISSUE TITLE
v2 export command edits v1 json files

### ISSUE THREAD

**Issue by Kordishal** [open5e/open5e-api#440]
Every time I run the export command there are a few changes made to the v1 data files. There are 8 files that are currently edited each time. I can easily roll these changes back, but it is an extra step.

![image](https://github.com/open5e/open5e-api/assets/14262536/ec31651c-9f94-4d5e-b2c3-429d076881d9)

As far as I can tell they are fully serialization changes that do not change the content itself in any way. For example for some resources the created_at field is changed to exclude the milliseconds part of the time. Another file is fully reformatted because it is indented differently than the exporter wants.

This could be resolved by either not exporting v1 resources with the exporter or by committing these changes once.

I think the first solution is the more sustained solution, but I am not sure how difficult it would be. Committing them would be quick to do, but might have to be redone in the future.

The export is not needed for the v1 resources as you cannot edit the resources via the Admin interface, and I doubt anyone would want to directly edit the sqlite3 database...

I can definitely do the second solution and make a PR and I can attempt the first one. What would you prefer?

**Comment by augustjohnson** [comment]
@Kordishal this is because of a timestamp field (created_at) that updates every time you run quicksetup.
#416 being resolved should theoretically fix this.

However, created_at is used as an input to v1 search (see https://github.com/open5e/open5e-api/blob/staging/api/search_indexes.py#L33). Unrelated, v1 search (the haystack library) also forces us to stay on django 3.1, where current is 5.0.

I am currently writing v2 search, which should fully replace v1 search, and allow us to deprecate and upgrade. After that switchover occurs, I think created_at can be straight removed with no impact.  You may be able to untangle it and remove it now if you'd like, I don't believe it's truly used for any meaningful feature.

**Comment by augustjohnson** [comment]
Interesting... I have intended to design MOST of the v2 objects as ONLY sorted by their keys, which are provided by the user and are just a string. The fact that it moves the halfling down is weird, possibly a bug in export?

Unicode character replacement is not crazy... maybe there's encoding differences between OS layer?  99% of this was originally created on my local (debian-based) machine, so if you're on windows or mac there could be something different there.

Additionally some of the unicode chararcters (the backtick in particular) are copy/pasted from the source PDFs and originate from there.  I'd like to standardize a single tick in our data, but it's mostly just an annoyance at the moment.

**Comment by augustjohnson** [comment]
This has been resolved, and no longer occurs. I have removed the created_at field across the spectrum.
