### ISSUE TITLE
Strange techie-looking "Sage Advice :class: official" headers

### ISSUE THREAD

**Issue by stuartlangridge** [open5e/open5e-api#51]
"Sage Advice" clarifications to rules seem to be shown with a header that looks like it needs formatting: see for example Uncanny Dodge https://beta.open5e.com/classes/rogue which shows:

![image](https://user-images.githubusercontent.com/4356350/75605949-cf478880-5adf-11ea-8a7f-e5a16a650fb4.png)

which looks like it should have been altered to be a pretty header and a formatted blockquote in some way, but hasn't been. The Sage Advice clarifications don't seem to be in this repository, so I can't look at patching it, but perhaps this is something that's currently already being worked on?

**Comment by augustjohnson** [comment]
This is actually a bug in the markdown file here:
https://github.com/open5e/open5e/blob/master/static/markdown/classes/rogue.md
Or possibly in the vue here:
https://github.com/open5e/open5e/blob/master/pages/classes/rogue.vue
The issue is that vue renderer does not seem to respect the blockquote.

I have logged https://github.com/open5e/open5e/issues/377 against the open5e project.
