### ISSUE TITLE
Fireball is listed as a cleric spell

### ISSUE THREAD

**Issue by michaeleconomy** [open5e/open5e-api#56]
https://open5e.com/spells/fireball

However, it is not a cleric spell....  maybe this has to do with the achetype stuff?

**Comment by michaeleconomy** [comment]
Also isn't most of the the archetype data in spells.json not part of the SRD?

anything: Cleric: Tempest, Cleric: Light, etc

**Comment by eepMoody** [comment]
I know this has been open for a bit, but we're kicking back into gear on development!

I believe it is listed as that because at least one cleric archetype gets access. Unfortunately WotC has gone the route of publishing their Spells with references to Archetypes that they're not actually putting out under OGL. I figured it was better to include as much info as I was allowed, even if I can't actually show the archetypes.

We're going to put some work into cleaning up the dataset, so hopefully we'll figure out the best solution for this soon.

**Comment by augustjohnson** [comment]
The framework for this is fixed in #222 which allows spells to be added to lists. For now, the only lists that I am creating are the class-based lists, not the subclass lists. We are only using subclasses that are actually in our API.
