### ISSUE TITLE
api.open5e.com dataset out of sync with master branch

### ISSUE THREAD

**Issue by daft-develop** [open5e/open5e-api#70]
Hello @eepMoody!

Really enjoy Open5e-api, thank you for all the work on setting it up.

I was going through some of the pull requests for fixes to the WotC SRD monsters.json and I've noticed a few commits to WoTC 5.1/monster.json don't appear on the live api.

One example:

on master, updated Giant Wasp correctly removes "swim speed" per #68 
https://github.com/eepMoody/open5e-api/blob/efcf490bed1152746b5a214847a2c7401db22fcf/data/WOTC_5e_SRD_v5.1/monsters.json#L8848

However, on the API, the original (incorrect) data is still present:
https://api.open5e.com/monsters/?challenge_rating=&armor_class=&type=&name=Giant+Wasp&document=&document__slug=

I suspect the Django database may just be out of date and needs a flush to rebuild against the WoTC .json's. I wasn't sure if this was something you simply did periodically, or it got missed.

**Comment by eepMoody** [comment]
I know it's been a while since this, but we did eventually get it updating again and I forgot to thank you! 

There were some issues with our CI/CD pipeline that I hadn't noticed, and they've been resolved. Also we are getting actively developing again, so if you have other ideas feel free to jump in!
